### ISSUE TITLE
RTCのビルドについて

### ISSUE THREAD

**Issue by Nobu19800** [yukimeat1999/GNG-Unk-Env-Navi_RTC#1]
マニュアルでRTCをビルドする際にVisual Studioでプロジェクトを開いてrandom.cppやslam.cpp等を追加する作業がありますが、基本的なCMakeの使用方法の話になりますが、src/CMakeLists.txtのset(comp_srcs～のところにrandom.cpp等のファイルを追加すれば対応できます。

**Comment by yukimeat1999** [comment]
ご指摘のあった、CMakeをソース、ヘッダーともに修正しました。

これに伴いマニュアルの修正も行いました。

**Comment by Nobu19800** [comment]
確認しました。対応していただきありがとうございます。
