### ISSUE TITLE
他の人のソースコードについて

### ISSUE THREAD

**Issue by Nobu19800** [yukimeat1999/GNG-Unk-Env-Navi_RTC#2]
UrgRTCのソースコードですが、これはGitHubのリポジトリがあるので、そのままソースコードをアップロードせずにサブモジュールとして追加する等した方がいいと思います。
違っていたら申し訳ないのですが、Serial.cpp、Serial.hは自作のソースコードではないと思うのですが、マニュアル等で特に使用したことについて書いていないようです。

**Comment by yukimeat1999** [comment]
UrgRTCをサブモジュールとして追加しました．
　これに伴い，UrgRTC-masterディレクトリを削除しました．

　研究室の先生に確認したところ，Serial.cpp及び，Serial.hのコードは別の用途で使うソースを持ってきていたようですが，今回のルンバを制御するためにソースコードを記述したため，殆んど自作のコードであり，使用した部分はありふれたポート接続のコードだそうです．
　これに伴い，Serial.cpp及び，Serial.hのコードの修正を行いました．

**Comment by Nobu19800** [comment]
ご確認ありがとうございます。問題ないと思います。
