### ISSUE TITLE
マニュアルについて

### ISSUE THREAD

**Issue by Nobu19800** [yukimeat1999/GNG-Unk-Env-Navi_RTC#3]
マニュアルにRTCの詳細な説明がないため、どういう機能があるのか分かりづらいです。
例えば、OutPort、InPortでどのようなデータを出力するのか、コンフィギュレーションパラメータで何の値を設定できるのか、という説明があったほうがいいと思います。

**Comment by yukimeat1999** [comment]
ご指摘の件につきまして、マニュアルに追記しました。

**Comment by Nobu19800** [comment]
対応していただきありがとうございます。このissueは閉じます。
